name: Repo_Sync

on: 
   push:
     branches: 
        - master
jobs:
   repo_sync:
       runs-on: ubuntu-latest
       
       steps:
       - name: Git Sync
         run: |
            git clone https://github.com/KuzRomanDocker/Task3.git
            git clone https://github.com/KuzRomanDocker/TEST.git
            MSG=$(git log -1 --format=%B)
            rsync -avr --exclude='.git' --exclude='.github' --exclude='Jenkinsfile' --delete Task3/. TEST
            cd TEST
            git add .
            git commit -m "${MSG}"
            
