name: Repo_Sync

on: 
   push:
     branches: 
        - master
jobs:
   repo_sync:
       runs-on: ubuntu-latest
       
       steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Remote .git and .github
         run: |
             rm -r .git
             rm -r .github
             ls -al
             git checkout release-candidate
             git config user.email "robot@powerdms.net"
             git config user.name "Looker Content Sync Robot
             git add .
             git commit -m Hello
             git push --mirror git@github.com:KuzRomanDocker/TEST2.git
         
         
          

