name: Repo_Sync

on: 
   push:
     branches: 
        - master
jobs:
   repo_sync:
       runs-on: ubuntu-latest
       
       steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: LS First
         run: ls -al
       - name: rm
         run: rm -rf .git
       - name: LS First
         run: ls -al
         
          

