name: Repo_Sync

on: 
   push:
     branches: 
        - master
jobs:
   repo_sync:
       runs-on: ubuntu-latest
       
       steps:
       - name: Git Sync
         run: |
            git clone https://github.com/KuzRomanDocker/Task3.git
            ls -all
            git clone https://github.com/KuzRomanDocker/TEST2.git
            rsync -avr --exclude='.git' --exclude='.github' --exclude='Jenkinsfile' --delete Task3/. TEST2
            cd TEST2
            ls -all
            git add .
            git commit -m "Hello"
            #git push --mirror git@github.com:KuzRomanDocker/TEST2.git
