name: Repo_Sync

on: 
   push:
     branches: 
        - master
jobs:
   repo_sync:
       runs-on: ubuntu-latest
       
       steps:
       - uses: actions/checkout@v2
       - name: Print Hello Message in Testing
         run: ls
