name: Repo_Sync

on: 
   push:
     branches: 
        - master
jobs:
   repo_sync:
       runs-on: ubuntu-latest
       
       steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Remote .git and .github
         run: |
             rm -r .git
             rm -r .github
   repo_clone:
       runs-on: ubuntu-latest
       needs: [repo_sync]
       
       steps:
       - name: Git Clone
         run: |
            git clone https://github.com/KuzRomanDocker/Jfizzbuzz.git         
            git add .
            git commit -m "Hello Word"
            git push --mirror git@github.com:KuzRomanDocker/fizzbuzz.git

