name: Repo_Sync

on: 
   push:
     branches: 
        - master
jobs:
   repo_sync:
       runs-on: ubuntu-latest
       
       steps:
       - uses: actions/checkout@v2
       - name: rsync deployments
         run: ls -al
       - name: ls remote
         run: ls https://github.com/KuzRomanDocker/Jenkins-pipeline/
         #uses: burnett01/rsync-deployments@4.1
         #with: 
         # switches: -avzr --delete --exclude='.git' --exclude='.github'
         # path: src/
          
