name: Repo_Sync

on: 
   push:
     branches: 
        - master
jobs:
   repo_sync:
       runs-on: ubuntu-latest
       
       steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: LS First
         run: ls -al
       - name: rm
         run: rm -r .git && rm -r .github
       - name: LS Two
         run: ls -al
       - name: GOGOGO
         run: |
             git remote add adobe https://github.com/KuzRomanDocker/Jenkins-pipeline.git
             git push --set-upstream adobe master
         
         
          

